from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]

# Runtime run switches now live at the top of main.py. This module keeps
# import-safe defaults for internal modules.

MACD_FAST = 8
MACD_SLOW = 21
MACD_SIGNAL = 5

EMA_PERIOD = 200
EMA_SLOPE_LOOKBACK = 20

RSI_PERIOD = 14
ADX_PERIOD = 14
CMF_PERIOD = 20
ATR_PERIOD = 14

ATRP_MEDIUM_RISK_PCT = 3.0
ATRP_HIGH_RISK_PCT = 5.0

SESSION_EXTENDED_MOVE_PCT = 5.0
SESSION_GAP_MOVE_PCT = 3.0

DEFAULT_LOOKBACK = "1y"

ENGINE_MODE_FULL_BASELINE = "FULL_BASELINE"
ENGINE_MODE_QUICK_CROSSOVER = "QUICK_CROSSOVER"
ENGINE_MODE_QUICK_SETUP = "QUICK_SETUP"

SUPPORTED_ENGINE_MODES = [
    ENGINE_MODE_FULL_BASELINE,
    ENGINE_MODE_QUICK_CROSSOVER,
    ENGINE_MODE_QUICK_SETUP
]

ENGINE_MODE = ENGINE_MODE_QUICK_SETUP
#ENGINE_MODE = ENGINE_MODE_QUICK_CROSSOVER

SETUP_PRICE_LOOKBACK_X = 5
SETUP_PRICE_MIN_ADVANCE_PCT = 0.5
SETUP_PRICE_USE_COMPLETED_DAILY_CLOSE = True

SETUP_PRIMARY_TIMEFRAME = "1d"
SETUP_BRIDGE_TIMEFRAME = "4h"
SETUP_TRIGGER_TIMEFRAME = "1h"
SETUP_MACD_HISTOGRAM_RISING_STREAK = 2

SETUP_REQUIRE_EMA200_BULL_ZONE = True
SETUP_REJECT_EXTENDED_UP = True
SETUP_REJECT_GAP_UP = False
SETUP_REJECT_HIGH_ATRP = False
SETUP_RSI_MIN = 45
SETUP_RSI_MAX = 78
SETUP_RSI_HEADROOM_FULL_SCORE_PCT = 35
SETUP_RSI_HEADROOM_MIN_SCORE_PCT = 10

SETUP_OUTPUT_ONLY_CONFIRMED = False

USE_LIVE_PRICE_FOR_DAILY = True
LIVE_PRICE_INTERVAL = "1m"
LIVE_PRICE_PERIOD = "1d"
LIVE_PRICE_PREPOST = False

DATA_INTERVALS = {
    "1h": "1h",
    "4h": "1h",
    "1d": "1d",
    "1w": "1wk"
}

DATA_PERIODS = {
    "1h": "30d",
    "4h": "60d",
    "1d": "5y",
    "1w": "5y"
}

BASELINE_FILE = str(
    PROJECT_ROOT /
    "STORAGE" /
    "ACTIVE_BASELINE.csv"
)

EXECUTION_REPORT_FILES = {
    ENGINE_MODE_FULL_BASELINE: str(
        PROJECT_ROOT /
        "OUTPUT" /
        "PMDE_EXECUTION_FULL_BASELINE_REPORT.csv"
    ),
    ENGINE_MODE_QUICK_CROSSOVER: str(
        PROJECT_ROOT /
        "OUTPUT" /
        "PMDE_EXECUTION_QUICK_CROSSOVER_REPORT.csv"
    ),
    ENGINE_MODE_QUICK_SETUP: str(
        PROJECT_ROOT /
        "OUTPUT" /
        "PMDE_EXECUTION_QUICK_SETUP_REPORT.csv"
    )
}

EXECUTION_REPORT_FILE = EXECUTION_REPORT_FILES.get(
    ENGINE_MODE,
    EXECUTION_REPORT_FILES[ENGINE_MODE_FULL_BASELINE]
)

INPUT_FILE = None
#INPUT_FILE = "D:/Tools/StockCodeMaster/01_NASDAQ_Sector_Energy_Nuclear.csv"

INPUT_SYMBOL_COLUMN = None

INPUT_EXCHANGE_COLUMN = None

DEFAULT_EXCHANGE = None

# Always merged into the run for quick ad-hoc analysis.
HARDCODED_SYMBOLS = ["UMAC", "NNE", "RDW", "RKLB"]

# Also merged into the run when populated; keep empty for no defaults.
FALLBACK_SYMBOLS = []

SORT_UNIQUE_SYMBOLS = False

FORCE_L2_ASSESSMENT = True

L1_PRICE_CHANGE_TRIGGER_PCT = 0.0

QUICK_CROSSOVER_OUTPUT_ONLY_PROBABLES = True

QUICK_CROSSOVER_STATES = [
    "PRE_BULL_CROSSOVER",
    "PRE_BEAR_CROSSOVER",
    "EARLY_RECOVERY_INSIDE_BEAR_STRUCTURE"
]

QUICK_CROSSOVER_BASELINE_STATES = [
    "PRE_BULL_CROSSOVER",
    "PRE_BEAR_CROSSOVER"
]

QUICK_CROSSOVER_INCLUDE_BASELINE_WATCHLIST = True
QUICK_CROSSOVER_INCLUDE_INPUT_SYMBOLS = True
QUICK_CROSSOVER_UPDATE_BASELINE = True

ACTIVE_GENERIC_FACTS = [
    "EMA200",
    "PRICE_CONTEXT",
    "SESSION_CONTEXT"
]

ACTIVE_INDICATORS = [
    "MACD",
    "PPO",
    "RSI",
    "ADX_DMI",
    "OBV",
    "CMF",
    "ATRP"
]

ACTIVE_CONTEXTS = []

MACD_TIMEFRAMES = [
    "1h",
    "4h",
    "1d"
]

PRIMARY_TECH_TIMEFRAME = "1d"

MARKET_CONTEXT_SYMBOLS = [
    "SPY",
    "QQQ",
    "^NSEI"
]

RELATED_INSTRUMENTS = {
    "AMD": [
        "AMDL",
        "ADMY",
        "AMDU",
        "AMDS"
    ]
}
